

ryanairApp.service('countriesService', function(){

  this.countries =  function(){
      return [
        {
          "code":"at",
          "name":"Austria",
          "seoName":"austria",
          "englishSeoName":"austria",
          "currency":"EUR",
          "url":"austria"
        },
        {
          "code":"be",
          "name":"Belgium",
          "seoName":"belgium",
          "englishSeoName":"belgium",
          "currency":"EUR",
          "url":"belgium"
        },
        {
          "code":"bg",
          "name":"Bulgaria",
          "seoName":"bulgaria",
          "englishSeoName":"bulgaria",
          "currency":"EUR",
          "url":"bulgaria"
        },
        {
          "code":"hr",
          "name":"Croatia",
          "seoName":"croatia",
          "englishSeoName":"croatia",
          "currency":"EUR",
          "url":"croatia"
        },
        {
          "code":"cy",
          "name":"Cyprus",
          "seoName":"cyprus",
          "englishSeoName":"cyprus",
          "currency":"EUR",
          "url":"cyprus"
        },
        {
          "code":"cz",
          "name":"Czech Republic",
          "seoName":"czech-republic",
          "englishSeoName":"czech-republic",
          "currency":"CZK",
          "url":"czech-republic"
        },
        {
          "code":"dk",
          "name":"Denmark",
          "seoName":"denmark",
          "englishSeoName":"denmark",
          "currency":"DKK",
          "url":"denmark"
        },
        {
          "code":"ee",
          "name":"Estonia",
          "seoName":"estonia",
          "englishSeoName":"estonia",
          "currency":"EUR",
          "url":"estonia"
        },
        {
          "code":"fi",
          "name":"Finland",
          "seoName":"finland",
          "englishSeoName":"finland",
          "currency":"EUR",
          "url":"finland"
        },
        {
          "code":"fr",
          "name":"France",
          "seoName":"france",
          "englishSeoName":"france",
          "currency":"EUR",
          "url":"france"
        },
        {
          "code":"de",
          "name":"Germany",
          "seoName":"germany",
          "englishSeoName":"germany",
          "currency":"EUR",
          "url":"germany"
        },
        {
          "code":"gr",
          "name":"Greece",
          "seoName":"greece",
          "englishSeoName":"greece",
          "currency":"EUR",
          "url":"greece"
        },
        {
          "code":"hu",
          "name":"Hungary",
          "seoName":"hungary",
          "englishSeoName":"hungary",
          "currency":"HUF",
          "url":"hungary"
        },
        {
          "code":"ie",
          "name":"Ireland",
          "seoName":"ireland",
          "englishSeoName":"ireland",
          "currency":"EUR",
          "url":"ireland"
        },
        {
          "code":"it",
          "name":"Italy",
          "seoName":"italy",
          "englishSeoName":"italy",
          "currency":"EUR",
          "url":"italy"
        },
        {
          "code":"lv",
          "name":"Latvia",
          "seoName":"latvia",
          "englishSeoName":"latvia",
          "currency":"EUR",
          "url":"latvia"
        },
        {
          "code":"lt",
          "name":"Lithuania",
          "seoName":"lithuania",
          "englishSeoName":"lithuania",
          "currency":"EUR",
          "url":"lithuania"
        },
        {
          "code":"mt",
          "name":"Malta",
          "seoName":"malta",
          "englishSeoName":"malta",
          "currency":"EUR",
          "url":"malta"
        },
        {
          "code":"me",
          "name":"Montenegro",
          "seoName":"montenegro",
          "englishSeoName":"montenegro",
          "currency":"EUR",
          "url":"montenegro"
        },
        {
          "code":"ma",
          "name":"Morocco",
          "seoName":"morocco",
          "englishSeoName":"morocco",
          "currency":"MAD",
          "url":"morocco"
        },
        {
          "code":"nl",
          "name":"Netherlands",
          "seoName":"netherlands",
          "englishSeoName":"netherlands",
          "currency":"EUR",
          "url":"netherlands"
        },
        {
          "code":"no",
          "name":"Norway",
          "seoName":"norway",
          "englishSeoName":"norway",
          "currency":"NOK",
          "url":"norway"
        },
        {
          "code":"pl",
          "name":"Poland",
          "seoName":"poland",
          "englishSeoName":"poland",
          "currency":"PLN",
          "url":"poland"
        },
        {
          "code":"pt",
          "name":"Portugal",
          "seoName":"portugal",
          "englishSeoName":"portugal",
          "currency":"EUR",
          "url":"portugal"
        },
        {
          "code":"ro",
          "name":"Romania",
          "seoName":"romania",
          "englishSeoName":"romania",
          "currency":"EUR",
          "url":"romania"
        },
        {
          "code":"sk",
          "name":"Slovakia",
          "seoName":"slovakia",
          "englishSeoName":"slovakia",
          "currency":"EUR",
          "url":"slovakia"
        },
        {
          "code":"es",
          "name":"Spain",
          "seoName":"spain",
          "englishSeoName":"spain",
          "currency":"EUR",
          "url":"spain"
        },
        {
          "code":"se",
          "name":"Sweden",
          "seoName":"sweden",
          "englishSeoName":"sweden",
          "currency":"SEK",
          "url":"sweden"
        },
        {
          "code":"ch",
          "name":"Switzerland",
          "seoName":"switzerland",
          "englishSeoName":"switzerland",
          "currency":"EUR",
          "url":"switzerland"
        },
        {
          "code":"gb",
          "name":"United Kingdom",
          "seoName":"united-kingdom",
          "englishSeoName":"united-kingdom",
          "currency":"GBP",
          "url":"united-kingdom"
        }
      ]

  };


});

angular.module('ryanairApp').service('cheapflightService', function(){

  this.cheaps = function(){

    return {
      "flights":[
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"346.56",
              "valueMainUnit":"346",
              "valueFractionalUnit":"56",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"274.40",
              "valueMainUnit":"274",
              "valueFractionalUnit":"40",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"185.97",
              "valueMainUnit":"185",
              "valueFractionalUnit":"97",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"242.21",
              "valueMainUnit":"242",
              "valueFractionalUnit":"21",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"462.28",
              "valueMainUnit":"462",
              "valueFractionalUnit":"28",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"175.56",
              "valueMainUnit":"175",
              "valueFractionalUnit":"56",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"497.32",
              "valueMainUnit":"497",
              "valueFractionalUnit":"32",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"475.94",
              "valueMainUnit":"475",
              "valueFractionalUnit":"94",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"72.86",
              "valueMainUnit":"72",
              "valueFractionalUnit":"86",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"377.19",
              "valueMainUnit":"377",
              "valueFractionalUnit":"19",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"406.54",
              "valueMainUnit":"406",
              "valueFractionalUnit":"54",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"169.66",
              "valueMainUnit":"169",
              "valueFractionalUnit":"66",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"216.36",
              "valueMainUnit":"216",
              "valueFractionalUnit":"36",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"490.71",
              "valueMainUnit":"490",
              "valueFractionalUnit":"71",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        },
        {
          "outbound":{
            "airportFrom":{
              "iataCode":"LGW",
              "name":"London Gatwick",
              "base":false,
              "latitude":51.1481,
              "longitude":-0.190278,
              "country":{
                "code":"gb",
                "name":"United Kingdom",
                "seoName":"united-kingdom",
                "englishSeoName":"united-kingdom",
                "currency":"GBP",
                "url":"united-kingdom"
              }
            },
            "airportTo":{
              "iataCode":"DUB",
              "name":"Dublin",
              "base":true,
              "latitude":53.4213,
              "longitude":-6.27007,
              "country":{
                "code":"ie",
                "name":"Ireland",
                "seoName":"ireland",
                "englishSeoName":"ireland",
                "currency":"EUR",
                "url":"ireland"
              }
            },
            "price":{
              "value":"256.60",
              "valueMainUnit":"256",
              "valueFractionalUnit":"60",
              "currencySymbol":"€"
            },
            "dateFrom":"2015-02-02T00:00:00+00:00",
            "dateTo":"2015-04-02T00:00:00+00:00"
          }
        }
      ],
      "count":15,
      "totalCount":15,
      "currency":{
        "symbol":"€",
        "maxPrice":"500",
        "defaultPrice":0
      },
      "currencySymbol":"€",
      "request":{
        "from":"LGW",
        "to":"DUB",
        "start_date":"2015-02-02",
        "end_date":"2015-04-02",
        "max_price":"500"
      }
    }


  }
});
